#!/usr/bin/env sh

#~~~~~~~~~~~~~~~~~#
# global settings #
#~~~~~~~~~~~~~~~~~#
# Layout
yabai -m config layout bsp

# Padding
yabai -m config top_padding    8
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

# Mouse related
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier fn
yabai -m config mouse_action_1 move
yabai -m config mouse_action_2 resize
yabai -m config mouse_drop_action swap

# Windows
yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config window_topmost on
yabai -m config window_placement second_child
yabai -m config auto_balance on

# Border
yabai -m config window_border_width 1
yabai -m config window_border_radius 12
yabai -m config window_border on
yabai -m config window_border_blur off
yabai -m config active_window_border_color 0xff7aa2f7

# Rules to ignore apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Microsoft Remote Desktop$" manage=off
